name: Run Pytest on Push

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the action on
      - "feature-*"  # Optional: Run on feature branches

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Change this to the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have a requirements.txt

      - name: Run Pytest
        run: pytest -v tests/
